/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Editor.Editor;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author bruno.191196
 */
public class Interface extends javax.swing.JFrame {

  /**
   * Creates new form Interface
   */
  public Interface() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    areaTexto = new javax.swing.JTextArea();
    jMenuBar1 = new javax.swing.JMenuBar();
    jMenu1 = new javax.swing.JMenu();
    arquivoAbrir = new javax.swing.JMenuItem();
    arquivoSalvarComo = new javax.swing.JMenuItem();
    jMenu2 = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    areaTexto.setColumns(20);
    areaTexto.setRows(5);
    jScrollPane1.setViewportView(areaTexto);

    jMenu1.setText("Arquivo");

    arquivoAbrir.setText("Abrir");
    arquivoAbrir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        arquivoAbrirActionPerformed(evt);
      }
    });
    jMenu1.add(arquivoAbrir);

    arquivoSalvarComo.setText("Salvar como...");
    arquivoSalvarComo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        arquivoSalvarComoActionPerformed(evt);
      }
    });
    jMenu1.add(arquivoSalvarComo);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Editar");
    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void arquivoSalvarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoSalvarComoActionPerformed
    javax.swing.JOptionPane jop = new javax.swing.JOptionPane();
    String s = (String)JOptionPane.showInputDialog(this, "Digite o nome do arquivo: ",
                                                   "Customized Dialog", JOptionPane.PLAIN_MESSAGE,
                                                   null, null, "");
    if ((s != null) && (s.length() > 0)) {
      ed = new Editor();
      if (s.contains(".txt") == false) {
        s = s.concat(".txt");
      }
      ed.escreverArquivo(s, areaTexto.getText());
    }
  }//GEN-LAST:event_arquivoSalvarComoActionPerformed

  private void arquivoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivoAbrirActionPerformed
    javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
    if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
      ed = new Editor();
      areaTexto.setText(ed.abrirArquivo(fileChooser.getSelectedFile()));
    }
  }//GEN-LAST:event_arquivoAbrirActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Interface().setVisible(true);
      }
    });
  }

  Editor ed;
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea areaTexto;
  private javax.swing.JMenuItem arquivoAbrir;
  private javax.swing.JMenuItem arquivoSalvarComo;
  private javax.swing.JMenu jMenu1;
  private javax.swing.JMenu jMenu2;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
